{% set name = "geoid-toolkit" %}
{% set version = "1.1.4" %}
{% set sha256 = "6fc6ac38fcadd588b4362ba2c302013f0291e51879b021b768a309f21e2359b5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://files.pythonhosted.org/packages/source/{{ name[0] }}/{{ name }}/geoid_toolkit-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - cartopy
    - gdal
    - h5py
    - lxml
    - matplotlib-base
    - netCDF4
    - numpy
    - platformdirs
    - pyproj
    - python >={{ python_min }}
    - python-dateutil

test:
  imports:
    - geoid_toolkit
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/tsutterley/geoid-toolkit
  summary: Python-based geoid and gravity calculation software
  license: MIT
  license_file: LICENSE
  description: |
    Python tools for obtaining and working with static
    gravity field coefficients and calculating geoid heights
  doc_url: https://geoid-toolkit.readthedocs.io/
  dev_url: https://github.com/tsutterley/geoid-toolkit

extra:
  recipe-maintainers:
    - tsutterley
